<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class StaffSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $staff = [
            [
                'tenant_id' => 1,
                'user_id' => null,
                'branch_id' => 1,
                'staff_number' => 'EMP-001',
                'first_name' => 'Musa',
                'last_name' => 'Ibrahim',
                'email' => 'musa@firstgiwa.com',
                'phone' => '08012345001',
                'address' => '15 Industrial Avenue, Ikeja, Lagos',
                'department' => 'Production',
                'position' => 'Production Manager',
                'employment_type' => 'full_time',
                'date_of_birth' => '1985-03-15',
                'date_hired' => '2022-03-15',
                'date_terminated' => null,
                'employment_status' => 'active',
                'basic_salary' => 350000.00,
                'salary_frequency' => 'monthly',
                'housing_allowance' => 50000.00,
                'transport_allowance' => 30000.00,
                'other_allowances' => 20000.00,
                'bank_name' => 'First Bank',
                'account_number' => '2012345678',
                'account_name' => 'Musa Ibrahim',
                'tax_id' => 'TIN-12345678',
                'national_id' => 'NIN-123456789012',
                'pension_number' => 'PEN-001234567',
                'emergency_contact_name' => 'Aisha Ibrahim',
                'emergency_contact_phone' => '08098765432',
                'emergency_contact_relationship' => 'Wife',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'user_id' => null,
                'branch_id' => 1,
                'staff_number' => 'EMP-002',
                'first_name' => 'Amina',
                'last_name' => 'Yusuf',
                'email' => 'amina@firstgiwa.com',
                'phone' => '08012345002',
                'address' => '22 Victoria Island, Lagos',
                'department' => 'Finance',
                'position' => 'Chief Accountant',
                'employment_type' => 'full_time',
                'date_of_birth' => '1988-08-20',
                'date_hired' => '2021-08-01',
                'date_terminated' => null,
                'employment_status' => 'active',
                'basic_salary' => 400000.00,
                'salary_frequency' => 'monthly',
                'housing_allowance' => 60000.00,
                'transport_allowance' => 40000.00,
                'other_allowances' => 25000.00,
                'bank_name' => 'GTBank',
                'account_number' => '0123456789',
                'account_name' => 'Amina Yusuf',
                'tax_id' => 'TIN-23456789',
                'national_id' => 'NIN-234567890123',
                'pension_number' => 'PEN-002345678',
                'emergency_contact_name' => 'Yusuf Abdullahi',
                'emergency_contact_phone' => '08087654321',
                'emergency_contact_relationship' => 'Father',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'user_id' => null,
                'branch_id' => 1,
                'staff_number' => 'EMP-003',
                'first_name' => 'Grace',
                'last_name' => 'Okonkwo',
                'email' => 'grace@firstgiwa.com',
                'phone' => '08012345003',
                'address' => '45 Lekki Phase 1, Lagos',
                'department' => 'Admin',
                'position' => 'Office Manager',
                'employment_type' => 'full_time',
                'date_of_birth' => '1990-01-10',
                'date_hired' => '2023-01-10',
                'date_terminated' => null,
                'employment_status' => 'active',
                'basic_salary' => 250000.00,
                'salary_frequency' => 'monthly',
                'housing_allowance' => 35000.00,
                'transport_allowance' => 25000.00,
                'other_allowances' => 15000.00,
                'bank_name' => 'UBA',
                'account_number' => '1234567890',
                'account_name' => 'Grace Okonkwo',
                'tax_id' => 'TIN-34567890',
                'national_id' => 'NIN-345678901234',
                'pension_number' => 'PEN-003456789',
                'emergency_contact_name' => 'Chukwu Okonkwo',
                'emergency_contact_phone' => '08076543210',
                'emergency_contact_relationship' => 'Brother',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'user_id' => null,
                'branch_id' => 1,
                'staff_number' => 'EMP-004',
                'first_name' => 'Bola',
                'last_name' => 'Adeyemi',
                'email' => 'bola@firstgiwa.com',
                'phone' => '08012345004',
                'address' => '78 Agege Motor Road, Lagos',
                'department' => 'Logistics',
                'position' => 'Logistics Coordinator',
                'employment_type' => 'full_time',
                'date_of_birth' => '1987-06-20',
                'date_hired' => '2023-06-20',
                'date_terminated' => null,
                'employment_status' => 'active',
                'basic_salary' => 280000.00,
                'salary_frequency' => 'monthly',
                'housing_allowance' => 40000.00,
                'transport_allowance' => 30000.00,
                'other_allowances' => 15000.00,
                'bank_name' => 'Zenith Bank',
                'account_number' => '9876543210',
                'account_name' => 'Bola Adeyemi',
                'tax_id' => 'TIN-45678901',
                'national_id' => 'NIN-456789012345',
                'pension_number' => 'PEN-004567890',
                'emergency_contact_name' => 'Folake Adeyemi',
                'emergency_contact_phone' => '08065432109',
                'emergency_contact_relationship' => 'Wife',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'user_id' => null,
                'branch_id' => 1,
                'staff_number' => 'EMP-005',
                'first_name' => 'Aisha',
                'last_name' => 'Bello',
                'email' => 'aisha@firstgiwa.com',
                'phone' => '08012345005',
                'address' => '33 Apapa Road, Lagos',
                'department' => 'Production',
                'position' => 'Production Supervisor',
                'employment_type' => 'full_time',
                'date_of_birth' => '1992-02-01',
                'date_hired' => '2024-02-01',
                'date_terminated' => null,
                'employment_status' => 'active',
                'basic_salary' => 200000.00,
                'salary_frequency' => 'monthly',
                'housing_allowance' => 25000.00,
                'transport_allowance' => 20000.00,
                'other_allowances' => 10000.00,
                'bank_name' => 'Access Bank',
                'account_number' => '5678901234',
                'account_name' => 'Aisha Bello',
                'tax_id' => 'TIN-56789012',
                'national_id' => 'NIN-567890123456',
                'pension_number' => 'PEN-005678901',
                'emergency_contact_name' => 'Mohammed Bello',
                'emergency_contact_phone' => '08054321098',
                'emergency_contact_relationship' => 'Father',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'user_id' => null,
                'branch_id' => 1,
                'staff_number' => 'EMP-006',
                'first_name' => 'Chidi',
                'last_name' => 'Eze',
                'email' => 'chidi@firstgiwa.com',
                'phone' => '08012345006',
                'address' => '12 Surulere, Lagos',
                'department' => 'Sales',
                'position' => 'Sales Representative',
                'employment_type' => 'full_time',
                'date_of_birth' => '1995-05-15',
                'date_hired' => '2024-05-15',
                'date_terminated' => null,
                'employment_status' => 'active',
                'basic_salary' => 180000.00,
                'salary_frequency' => 'monthly',
                'housing_allowance' => 20000.00,
                'transport_allowance' => 20000.00,
                'other_allowances' => 10000.00,
                'bank_name' => 'First Bank',
                'account_number' => '3456789012',
                'account_name' => 'Chidi Eze',
                'tax_id' => 'TIN-67890123',
                'national_id' => 'NIN-678901234567',
                'pension_number' => 'PEN-006789012',
                'emergency_contact_name' => 'Ngozi Eze',
                'emergency_contact_phone' => '08043210987',
                'emergency_contact_relationship' => 'Mother',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'user_id' => null,
                'branch_id' => 1,
                'staff_number' => 'EMP-007',
                'first_name' => 'Fatima',
                'last_name' => 'Abdullahi',
                'email' => 'fatima@firstgiwa.com',
                'phone' => '08012345007',
                'address' => '56 Yaba, Lagos',
                'department' => 'Finance',
                'position' => 'Cashier',
                'employment_type' => 'full_time',
                'date_of_birth' => '1996-09-01',
                'date_hired' => '2024-09-01',
                'date_terminated' => null,
                'employment_status' => 'active',
                'basic_salary' => 150000.00,
                'salary_frequency' => 'monthly',
                'housing_allowance' => 15000.00,
                'transport_allowance' => 15000.00,
                'other_allowances' => 8000.00,
                'bank_name' => 'GTBank',
                'account_number' => '7890123456',
                'account_name' => 'Fatima Abdullahi',
                'tax_id' => 'TIN-78901234',
                'national_id' => 'NIN-789012345678',
                'pension_number' => 'PEN-007890123',
                'emergency_contact_name' => 'Halima Abdullahi',
                'emergency_contact_phone' => '08032109876',
                'emergency_contact_relationship' => 'Sister',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'user_id' => null,
                'branch_id' => 1,
                'staff_number' => 'EMP-008',
                'first_name' => 'Ibrahim',
                'last_name' => 'Sanni',
                'email' => null,
                'phone' => '08012345008',
                'address' => '89 Oshodi, Lagos',
                'department' => 'Production',
                'position' => 'Machine Operator',
                'employment_type' => 'contract',
                'date_of_birth' => '1993-01-10',
                'date_hired' => '2025-01-10',
                'date_terminated' => null,
                'employment_status' => 'active',
                'basic_salary' => 120000.00,
                'salary_frequency' => 'monthly',
                'housing_allowance' => 0,
                'transport_allowance' => 15000.00,
                'other_allowances' => 5000.00,
                'bank_name' => 'Wema Bank',
                'account_number' => '4567890123',
                'account_name' => 'Ibrahim Sanni',
                'tax_id' => null,
                'national_id' => 'NIN-890123456789',
                'pension_number' => null,
                'emergency_contact_name' => 'Sanni Musa',
                'emergency_contact_phone' => '08021098765',
                'emergency_contact_relationship' => 'Father',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'user_id' => null,
                'branch_id' => 1,
                'staff_number' => 'EMP-009',
                'first_name' => 'Ngozi',
                'last_name' => 'Okafor',
                'email' => 'ngozi@firstgiwa.com',
                'phone' => '08012345009',
                'address' => '23 Mushin, Lagos',
                'department' => 'Admin',
                'position' => 'Receptionist',
                'employment_type' => 'full_time',
                'date_of_birth' => '1998-06-01',
                'date_hired' => '2025-06-01',
                'date_terminated' => null,
                'employment_status' => 'active',
                'basic_salary' => 100000.00,
                'salary_frequency' => 'monthly',
                'housing_allowance' => 10000.00,
                'transport_allowance' => 12000.00,
                'other_allowances' => 5000.00,
                'bank_name' => 'Union Bank',
                'account_number' => '6789012345',
                'account_name' => 'Ngozi Okafor',
                'tax_id' => 'TIN-90123456',
                'national_id' => 'NIN-901234567890',
                'pension_number' => 'PEN-009012345',
                'emergency_contact_name' => 'Emeka Okafor',
                'emergency_contact_phone' => '08010987654',
                'emergency_contact_relationship' => 'Brother',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'user_id' => null,
                'branch_id' => 1,
                'staff_number' => 'EMP-010',
                'first_name' => 'Ahmed',
                'last_name' => 'Lawal',
                'email' => null,
                'phone' => '08012345010',
                'address' => '67 Ikorodu Road, Lagos',
                'department' => 'Logistics',
                'position' => 'Driver',
                'employment_type' => 'contract',
                'date_of_birth' => '1980-11-15',
                'date_hired' => '2024-11-15',
                'date_terminated' => null,
                'employment_status' => 'on_leave',
                'basic_salary' => 95000.00,
                'salary_frequency' => 'monthly',
                'housing_allowance' => 0,
                'transport_allowance' => 0,
                'other_allowances' => 10000.00,
                'bank_name' => 'First Bank',
                'account_number' => '8901234567',
                'account_name' => 'Ahmed Lawal',
                'tax_id' => null,
                'national_id' => 'NIN-012345678901',
                'pension_number' => null,
                'emergency_contact_name' => 'Hauwa Lawal',
                'emergency_contact_phone' => '08009876543',
                'emergency_contact_relationship' => 'Wife',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('staff')->insert($staff);

        $this->command->info('Staff seeder completed: ' . count($staff) . ' staff members created');
    }
}
